---
language: python
python: "3.6"
sudo: required
group: deprecated-2017Q4

services:
  - docker
install:
  - pip install -r test-requirements.txt
script:
  - molecule test --all

env:
  jobs:
    - DOCKER_IMAGE_BASE=idealista/jdk:8u265-stretch-openjdk-headless
    - DOCKER_IMAGE_BASE=idealista/jdk:8u265-buster-adoptopenjdk-headless
    - DOCKER_IMAGE_BASE=idealista/jdk:8u292-bullseye-adoptopenjdk-headless


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
