---

- name: NEXUS | Install
  import_tasks: install.yml
  tags:
    - install

# - name: NEXUS | Agents configuration
#   import_tasks: agent.yml
#   tags:
#     - agent_config
#   when: nexus_agents_config is defined

- name: NEXUS | Configure Service
  import_tasks: config.yml
  tags:
    - configure

- name: NEXUS | Service
  import_tasks: service.yml
  tags:
    - service

- name: NEXUS | Configure Nexus
  import_tasks: config_nexus.yml
  tags:
    - configure_nexus
