---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: nexus-test
    image: ${DOCKER_BASE_IMAGE:-idealista/jdk:8u292-bullseye-adoptopenjdk-headless}
    privileged: true
    pre_build_image: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    groups:
      - nexus
    command: '/lib/systemd/systemd'

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False
verifier:
  name: goss
  lint:
    name: yamllint
    enabled: False
